import React, { useState, useRef } from 'react';
import { Upload, FileText, X, ChevronRight, AlertCircle, Shield } from 'lucide-react';

interface BrandGuidelinesModalProps {
  onComplete: (active: boolean) => void;
}

const BrandGuidelinesModal: React.FC<BrandGuidelinesModalProps> = ({ onComplete }) => {
  const [files, setFiles] = useState<(File | null)[]>([null, null]);
  const fileInputRefs = [useRef<HTMLInputElement>(null), useRef<HTMLInputElement>(null)];

  const handleFileChange = (index: number, e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) {
      const newFiles = [...files];
      newFiles[index] = e.target.files[0];
      setFiles(newFiles);
    }
  };

  const removeFile = (index: number) => {
    const newFiles = [...files];
    newFiles[index] = null;
    setFiles(newFiles);
    if (fileInputRefs[index].current) {
        fileInputRefs[index].current!.value = '';
    }
  };

  const hasFiles = files.some(f => f !== null);

  return (
    <div className="fixed inset-0 z-[100] bg-black/90 backdrop-blur-xl flex items-center justify-center p-4 animate-in fade-in duration-500">
      <div className="w-full max-w-2xl bg-macdonald-dark border border-macdonald-gold/30 shadow-[0_0_50px_rgba(197,160,89,0.2)] relative overflow-hidden flex flex-col">
        
        {/* Header */}
        <div className="p-8 border-b border-white/10 bg-gradient-to-r from-macdonald-green/50 to-transparent">
            <div className="flex items-center gap-3 mb-2">
                <Shield className="text-macdonald-gold" size={24} />
                <h2 className="text-2xl font-bold uppercase text-white tracking-widest">System Initialization</h2>
            </div>
            <p className="text-gray-400 text-sm">To ensure 100% brand compliance generated by Gemini AI, please upload your Brand Guidelines.</p>
        </div>

        {/* Body */}
        <div className="p-8 space-y-6">
            
            {/* Upload Slots */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {[0, 1].map((index) => (
                    <div key={index}>
                        <input 
                            type="file" 
                            accept=".pdf" 
                            className="hidden" 
                            // @ts-ignore
                            ref={fileInputRefs[index]} 
                            onChange={(e) => handleFileChange(index, e)} 
                        />
                        <div 
                            onClick={() => !files[index] && fileInputRefs[index].current?.click()}
                            className={`
                                h-40 border-2 border-dashed transition-all cursor-pointer flex flex-col items-center justify-center p-4 text-center relative group
                                ${files[index] 
                                    ? 'border-macdonald-gold bg-macdonald-gold/10' 
                                    : 'border-white/20 hover:border-macdonald-gold/50 hover:bg-white/5'
                                }
                            `}
                        >
                            {files[index] ? (
                                <>
                                    <FileText size={32} className="text-macdonald-gold mb-2" />
                                    <span className="text-white text-xs font-bold truncate w-full">{files[index]?.name}</span>
                                    <button 
                                        onClick={(e) => { e.stopPropagation(); removeFile(index); }}
                                        className="absolute top-2 right-2 text-red-400 hover:text-white"
                                    >
                                        <X size={16} />
                                    </button>
                                </>
                            ) : (
                                <>
                                    <Upload size={24} className="text-gray-500 mb-2 group-hover:text-macdonald-gold" />
                                    <span className="text-gray-400 text-xs uppercase font-bold">Upload PDF {index + 1}</span>
                                    <span className="text-gray-600 text-[10px] mt-1">Brand Guidelines / Tone of Voice</span>
                                </>
                            )}
                        </div>
                    </div>
                ))}
            </div>

            <div className="flex items-start gap-3 bg-blue-500/10 border border-blue-500/20 p-4">
                <AlertCircle size={18} className="text-blue-400 mt-1 shrink-0" />
                <p className="text-xs text-blue-200">
                    <strong>Strongly Recommended:</strong> Without these documents, the AI will use generic luxury hotel training data. Uploading specifics ensures font, color, and voice accuracy.
                </p>
            </div>

        </div>

        {/* Footer */}
        <div className="p-6 bg-black/40 border-t border-white/10 flex justify-between items-center">
            <button 
                onClick={() => onComplete(false)}
                className="text-xs text-gray-500 hover:text-white uppercase tracking-widest px-4 py-2 hover:bg-white/5 transition-colors"
            >
                Skip Setup
            </button>

            <button 
                onClick={() => onComplete(hasFiles)}
                className={`
                    px-8 py-3 font-bold uppercase tracking-widest flex items-center gap-2 skew-x-[-10deg] transition-all
                    ${hasFiles ? 'bg-macdonald-gold text-black hover:bg-white' : 'bg-gray-800 text-gray-500 border border-gray-700'}
                `}
            >
                <span className="skew-x-[10deg]">{hasFiles ? 'Initialize Workbench' : 'Continue Default'}</span>
                <ChevronRight size={16} className="skew-x-[10deg]" />
            </button>
        </div>

      </div>
    </div>
  );
};

export default BrandGuidelinesModal;